version: "3"
services:
    redis:
        image: "redis"
        ports:
            - "6379:6379"

    redisinsight:
        image: redislabs/redisinsight:latest
        ports:
            - "8001:8001"
    
    postgres:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: id6
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: nopwd
        volumes:
            - pg:/var/lib/postgresql/data
    
    adminer:
        image: library/adminer:latest
        restart: always
        ports:
            - 7777:8080

#    web:
#        build:
#            context: .
#            dockerfile: Dockerfile.web
#        ports:
#            - "8080:8080"
#        depends_on:
#            - postgres
#        links:
#            - postgres
#    
#    migrating:
#        build:
#            context: .
#            dockerfile: Dockerfile.test
#        command:
#            - sh
#            - -c
#            - |
#                echo "start migrating database"
#                
#                echo "start running tests"
#                
#                dotnet test
#                
#                echo "testing done"
#        links:
#            - postgres
#        depends_on:
#            - postgres
#            - web

volumes:
    pg: ~
